// Every string the platform console shows, in both languages.
//
// Kept out of the components on purpose: the console is one screen per admin job, and the
// alternative — a dictionary per view — is how a product ends up with three spellings of
// "subscription". One file also makes it obvious when an English key has no Arabic twin.
import type { Dict } from '../../lib/i18n';

export const DICT: Dict = {
  ar: { restaurants: 'المطاعم', cur: 'ر.ع', logoutT: 'خروج',
        kTotal: 'إجمالي المطاعم', kActive: 'نشِطة', kInactive: 'موقوفة', kNew: 'جديدة هذا الشهر',
        kOrders30: 'طلبات آخر ٣٠ يوم', kRevenue30: 'إيرادات آخر ٣٠ يوم',
        search: 'ابحث بالاسم أو المعرّف…', all: 'الكل', active: 'نشِط', inactive: 'موقوف', newR: '＋ مطعم جديد',
        thName: 'المطعم', thContact: 'التواصل', thVat: 'الضريبة', thStatus: 'الحالة', thCreated: 'الإنشاء',
        thOrders30: 'طلبات ٣٠ يوم', thRevenue30: 'إيراد ٣٠ يوم', thLastOrder: 'آخر طلب',
        featTitle: 'ما تشمله كل خطة', featCol: 'الميزة',
        featSub: 'تغيير أي مربّع ينطبق فوراً على كل المقاهي في تلك الخطة.',
        featOnConfirm: 'تفعيل هذه الميزة لكل المقاهي في هذه الخطة؟',
        featOffConfirm: 'إيقاف هذه الميزة عن كل المقاهي في هذه الخطة؟',
        feat_PRO_ANALYTICS: 'التحليلات المتقدّمة', featd_PRO_ANALYTICS: 'المسار، تحويل الأصناف، سلّة الشراء، الموظفون، التوقّع',
        feat_FULL_HISTORY: 'كامل السجلّ', featd_FULL_HISTORY: 'الاستعلام عن أي مدى زمني بدل نافذة قصيرة',
        feat_LOYALTY: 'برنامج الولاء', featd_LOYALTY: 'الأختام والمكافآت وإدارة الأعضاء',
        feat_MULTI_BRANCH: 'فروع متعدّدة', featd_MULTI_BRANCH: 'أكثر من فرع واحد',
        feat_QR_CUSTOMIZATION: 'تخصيص رمز QR', featd_QR_CUSTOMIZATION: 'الشعار واللون والخط في الرمز',
        close: 'إغلاق', priceFromPlan: 'من سعر الخطة — إنتربرايز فقط قابل للتفاوض', tierFromSub: 'يُحدَّد من الاشتراك', tierChangeWarn: '⚠ تغيير الخطة يغيّر ما يستطيع المقهى استخدامه فور الحفظ.', dwLive: 'يعمل فعليًا', dwNotLive: 'قيد التجهيز', dwStepsDone: 'من ٥ خطوات',
        dwFix: 'أكمِل', dwGoBilling: 'الفوترة والدفعات', dwGoHistory: 'سجل هذا المقهى',
        dwPaidTo: 'مدفوع حتى', dwNoSub: 'لا اشتراك', dwLastChange: 'آخر تغيير', dwNoChange: 'لا تغييرات',
        dwDetails: 'بيانات المقهى', dwMore: 'المزيد', dwContact: 'التواصل',
        dwToday: 'اليوم', dw30d: '٣٠ يوم', dwRev: 'الإيراد',
        billForCafe: 'عرض مقهى واحد', billClearFocus: '✕ اعرض الكل',
        auditForCafe: 'سجل مقهى واحد', auditClearFocus: '✕ اعرض الكل',
        activity: 'النشاط', aToday: 'طلبات اليوم', a30d: 'طلبات آخر ٣٠ يوم', aRev30: 'إيرادات آخر ٣٠ يوم (مكتملة)',
        aTotal: 'إجمالي الطلبات', aBranches: 'الفروع', aItems: 'أصناف القائمة', aLast: 'آخر طلب',
        never: 'لا طلبات بعد', justNow: 'الآن', minAgo: 'د', hrAgo: 'س', dayAgo: 'يوم',
        info: 'المعلومات', slug: 'المعرّف', phone: 'الهاتف', email: 'البريد', vat: 'القيمة المضافة', created: 'الإنشاء', currency: 'العملة',
        subscription: 'الاشتراك', plan: 'الخطة', cycle: 'الدورة', price: 'السعر', status: 'الحالة', noSub: 'لا يوجد اشتراك', addSub: 'إضافة اشتراك', editSub: 'تعديل الاشتراك',
        oneTime: 'دفع مرة واحدة', lifetime: 'مدى الحياة',
        endDate: 'ينتهي', renew: 'تجديد', renewed: 'تم التجديد الاشتراك', expired: 'منتهٍ', expiringSoon: 'قريب الانتهاء',
        activate: 'تفعيل', deactivate: 'إيقاف', save: 'حفظ', cancel: 'إلغاء', create: 'إنشاء',
        createT: 'إنشاء مطعم', createP: 'يُنشأ المطعم مع فرع وحساب المالك (اختياري) والاشتراك.',
        rName: 'اسم المطعم', rNameAr: 'الاسم بالعربية', rNameEn: 'الاسم بالإنجليزية',
        nameHint: 'الاسم يظهر بلغة الواجهة التي يستخدمها العميل. املأ اللغتين حتى لا تظهر العربية داخل واجهة إنجليزية.',
        rSlug: 'المعرّف (slug)', rPlan: 'الخطة', rBranch: 'اسم الفرع الأول', rPlanStd: 'قياسي', rPlanPro: 'Pro', rPlanEnt: 'Enterprise',
        oName: 'اسم المالك', oNameAr: 'اسم المالك بالعربية', oNameEn: 'اسم المالك بالإنجليزية', oEmail: 'بريد المالك', oPass: 'كلمة المرور',
        loginTitle: 'منصّة Serva.', loginSub: 'دخول مدير المنصّة', createdOk: 'تم الإنشاء', saved: 'تم الحفظ', enabled: 'مفعّل', disabled: 'متوقف',
        planLabel: 'الخطة',
        branches: 'الفروع', branchesAdd: '＋ فرع', branchName: 'اسم الفرع',
        branchNameAr: 'اسم الفرع بالعربية', branchNameEn: 'اسم الفرع بالإنجليزية', branchAddr: 'العنوان', branchPhone: 'الهاتف',
        branchAddOk: 'تم إنشاء الفرع', branchAdding: 'جارٍ…', noBranches: 'لا فروع بعد', deactivateBranch: 'إيقاف', activateBranch: 'تفعيل',
        profile: 'الملف الشخصي', editProfile: 'تعديل الملف الشخصي', editProfileSub: 'غيّر اسمك ورقم هاتفك على حساب المنصّة.',
        fullName: 'الاسم الكامل', fullNameAr: 'الاسم بالعربية', fullNameEn: 'الاسم بالإنجليزية', profileSaved: 'تم حفظ الملف الشخصي',
        language: 'اللغة', arabic: 'العربية', english: 'English',
        changePassword: 'تغيير كلمة المرور', changeEmail: 'تغيير البريد الإلكتروني',
        changePwSub: 'أدخل كلمة المرور الحالية ثم الجديدة.', changeEmailSub: 'أدخل كلمة المرور الحالية والبريد الجديد.',
        currentPw: 'كلمة المرور الحالية', newPw: 'كلمة المرور الجديدة', confirmPw: 'تأكيد كلمة المرور', newEmail: 'البريد الجديد',
        pwChanged: 'تم تغيير كلمة المرور', pwTooShort: 'كلمة المرور 8 أحرف على الأقل', pwMismatch: 'كلمتا المرور غير متطابقتين',
        emailChanged: 'تم تغيير البريد الإلكتروني', emailInvalid: 'أدخل بريدًا صحيحًا', role_PLATFORM_ADMIN: 'مشرف المنصة',
        navRestaurants: 'المطاعم', navPlans: 'الخطط',
        plansTitle: 'خطط الأسعار', plansSub: 'عدّل سعر كل فئة. الفئة هي ما يحدّد ميزات المطعم. الأسعار بالريال العماني.',
        colTier: 'الفئة', colName: 'الاسم', colMonthly: 'شهري', colSetup: 'رسوم التأسيس', colStatus: 'الحالة', colUnlocks: 'يتضمّن',
        edit: 'تعديل', planNamePh: 'الاسم المعروض', planSaved: 'تم حفظ الخطة',
        priceChangeWarn: 'سيُطبَّق السعر الجديد فورًا على كل المقاهي في هذه الفئة.',
        perMo: '/شهر', planOn: 'مفعّلة', planOff: 'مخفية', custom: 'مخصّص', choosePlan: 'اختر الفئة', setupShort: 'تأسيس',
        tierStdDesc: 'لوحة التحكم الأساسية', tierProDesc: '+ التحليلات المتقدّمة', tierEntDesc: '+ محجوزة / اتفاقية خدمة',
        menuSect: 'القائمة', importMenu: '⇪ استيراد قائمة (JSON)', importTitle: 'استيراد القائمة (JSON)',
        importHint: 'الصق القائمة كاملةً بصيغة JSON (أقسام وأصناف). الصور تُضاف يدوياً لاحقاً. سيستبدل هذا قائمة المطعم الحالية بالكامل.',
        importPlace: 'الصق JSON هنا…', importSample: 'إدراج نموذج', importReview: 'مراجعة', importBad: 'JSON غير صالح',
        importWarn: 'سيُحذف كل ما في قائمة هذا المطعم الآن ثم يُستبدل بما في الـ JSON. لا يمكن التراجع.',
        willDelete: 'سيُحذف', willAdd: 'سيُضاف', importConfirm: 'استبدال القائمة', importing: 'جارٍ الاستيراد…',
        importDoneT: 'تم الاستيراد', importErrorsT: 'أخطاء', closeBtn: 'إغلاق', catsWord: 'أقسام', itemsWord: 'أصناف',
        // pipeline
        navPipeline: 'الطلبات الواردة', pipelineTitle: 'الطلبات الواردة', 
        pipeSub: 'طلبات المقاهي القادمة من صفحة التعريف. حرّكها حتى تصبح مقهى فعليًا.',
        pipeNew: 'جديد', pipeContacted: 'تم التواصل', pipeConverted: 'تم التحويل', pipeArchived: 'مؤرشف',
        pipeEmpty: 'لا شيء هنا', pipeAll: 'الكل', pipeWaiting: 'بانتظار الرد منذ',
        pipeCall: 'تم الاتصال', pipeArchive: 'أرشفة', pipeReopen: 'إعادة فتح', pipeConvert: '➜ أنشئ المقهى',
        pipeNote: 'ملاحظات المكالمة', pipeNotePh: 'ماذا قالوا؟ متى نعاود الاتصال؟',
        pipeTheirNote: 'ما كتبوه', pipeSaveNote: 'حفظ الملاحظة', pipeNoteSaved: 'تم حفظ الملاحظة',
        pipeCity: 'المدينة', pipeOpenCafe: 'فتح المقهى', pipeContactedAt: 'تم التواصل',
        // onboarding wizard
        wizTitle: 'تشغيل مقهى جديد', wizFromLead: 'من طلب وارد',
        wizStep1: 'المقهى', wizStep2: 'المالك', wizStep3: 'الاشتراك', wizStep4: 'المراجعة',
        wizNext: 'التالي', wizBack: 'السابق', wizFinish: 'إنشاء المقهى', wizCreating: 'جارٍ الإنشاء…',
        wizNeedName: 'أدخل الاسم بلغة واحدة على الأقل',
        wizNeedSlug: 'لا يوجد اسم إنجليزي لاشتقاق العنوان منه. اكتب المعرّف بالأحرف اللاتينية — هو عنوان المقهى على الويب.',
        wizNeedOwner: 'أدخل بريد المالك وكلمة مرور من ٨ أحرف على الأقل — أو أوقف إنشاء حساب المالك.',
        wizOwnerSkip: 'يمكن إضافة المالك لاحقًا — سيُنشأ المقهى بدون حساب دخول.',
        wizOwnerHint: 'يستلم المالك بريدًا بمعلومات الدخول فور الإنشاء.',
        wizSubHint: 'يبدأ الاشتراك تجريبيًا. سجّل الدفعة من لوحة الفوترة لتحويله إلى نشِط.',
        wizReviewHint: 'راجع قبل الإنشاء — يُنشأ المقهى والفرع الأول وحساب المالك والاشتراك دفعة واحدة.',
        wizNoOwner: 'بدون حساب مالك', wizOwnerToggle: 'أنشئ حساب المالك الآن',
        // activation checklist
        actTitle: 'قائمة التشغيل', actDone: 'مكتمل', actLeft: 'ناقص',
        actOwner: 'حساب المالك', actBranch: 'فرع', actMenu: 'أصناف القائمة', actTables: 'طاولات QR', actOrder: 'أول طلب',
        actLive: 'يعمل فعليًا', actSetup: 'قيد التجهيز',
        // billing
        navBilling: 'الفوترة', billTitle: 'الفوترة والتجديدات',
        billMrr: 'الإيراد الشهري المتكرر', billArr: 'سنويًا', billThisMonth: 'محصّل هذا الشهر',
        billLastMonth: 'الشهر الماضي', billOutstanding: 'مستحق التحصيل',
        billQAll: 'الكل', billQOverdue: 'متأخر', billQExpiring: 'قارب الانتهاء', billQTrial: 'تجريبي', billQActive: 'نشِط',
        billCafe: 'المقهى', billPlan: 'الخطة', billPrice: 'السعر', billEnds: 'ينتهي', billLastPaid: 'آخر دفعة',
        billPaidTotal: 'إجمالي المدفوع', billDaysLeft: 'يوم', billOverdueBy: 'متأخر',
        billRecord: 'تسجيل دفعة', billRecordT: 'تسجيل دفعة',
        billAmount: 'المبلغ', billMethod: 'الطريقة', billRef: 'رقم الحوالة', billPaidOn: 'تاريخ الدفع',
        billNote: 'ملاحظة', billExtend: 'مدّد الفترة وفعّل الاشتراك',
        billExtendHint: 'أوقفه لتسجيل دفعة جزئية أو تصحيح دون تغيير التواريخ.',
        billSaved: 'تم تسجيل الدفعة', billHistory: 'سجل الدفعات', billNoPayments: 'لا دفعات مسجّلة',
        billRefund: 'المبلغ السالب = استرجاع أو تصحيح',
        // people
        navPeople: 'المستخدمون', peopleTitle: 'المستخدمون',
        peopleSub: 'كل حسابات المنصّة. من هنا تُعيد لمالك مقهى الدخول إلى حسابه.',
        peopleUser: 'المستخدم', peopleCafe: 'المقهى', peopleRole: 'الصلاحية', peopleStatus: 'الحالة',
        peopleOwner: 'مالك', peopleStaff: 'موظف', peopleAdmin: 'مشرف منصة', peoplePending: 'دعوة معلّقة',
        peopleReset: 'كلمة مرور جديدة', peopleResetT: 'تعيين كلمة مرور',
        peopleResetSub: 'تُنشأ كلمة مرور مؤقتة وتُعرض مرة واحدة. لن تظهر مرة أخرى.',
        peopleResetGo: 'تعيين وعرضها', peopleResetDone: 'كلمة المرور المؤقتة',
        peopleResetMailed: 'أُرسلت أيضًا بالبريد', peopleResetNotMailed: 'لا بريد على الحساب — اقرأها عليه.',
        peopleCopy: 'نسخ', peopleCopied: 'تم النسخ', peopleNoCafe: 'المنصّة',
        // impersonation
        impEnter: '⇥ ادخل كمقهى', impTitle: 'جلسة دعم',
        impSub: 'ستفتح لوحة المقهى بصلاحيات المالك لمدة ٣٠ دقيقة، وتُسجَّل العملية.',
        impGo: 'ادخل الآن', impBanner: 'أنت داخل', impExit: 'عودة إلى لوحة المنصّة',
        impLeft: 'متبقٍ', impStarted: 'تم فتح جلسة الدعم',
        // audit
        navAudit: 'السجل', auditTitle: 'سجل العمليات',
        auditSub: 'كل ما فعله مشرفو المنصّة. للقراءة فقط.',
        auditWho: 'من', auditWhat: 'ماذا', auditTarget: 'على', auditWhen: 'متى', auditEmpty: 'لا عمليات بعد',
        act_CAFE_CREATED: 'إنشاء مقهى', act_CAFE_ACTIVATED: 'تفعيل مقهى', act_CAFE_DEACTIVATED: 'إيقاف مقهى',
        act_CAFE_RENEWED: 'تجديد اشتراك', act_PLAN_CHANGED: 'تغيير الخطة',
        act_LEAD_CONVERTED: 'تحويل طلب وارد', act_SUBSCRIPTION_CHANGED: 'تعديل اشتراك', act_PAYMENT_RECORDED: 'تسجيل دفعة',
        act_PASSWORD_RESET: 'تعيين كلمة مرور', act_USER_DEACTIVATED: 'إيقاف مستخدم', act_USER_ACTIVATED: 'تفعيل مستخدم',
        act_IMPERSONATED: 'جلسة دعم', act_BROADCAST_SENT: 'تعميم', act_MENU_IMPORTED: 'استيراد قائمة',
        // health
        navHealth: 'الصحّة', healthTitle: 'صحّة المنصّة',
        healthRadar: 'مقاهٍ تحتاج انتباهًا', healthRadarSub: 'ترتيب حسب الأسوأ: صامتة، أو حجمها ينخفض، أو لم تُشغَّل أصلاً.',
        healthAllWell: 'كل المقاهي بخير', healthWhy: 'السبب',
        whySilent: 'صامت', whyDropping: 'انخفاض', whyNeverLive: 'لم يبدأ', whySetup: 'تجهيز ناقص',
        healthDays: 'يوم بلا طلب', healthDrop: 'مقارنة بالأسبوع الماضي',
        healthTrends: 'الاتجاه', trendOrders: 'الطلبات', trendRevenue: 'الإيراد', trendSignups: 'مقاهٍ جديدة',
        trend30: '٣٠ يوم', trend90: '٩٠ يوم', trend365: 'سنة',
        // broadcast
        bcTitle: 'تعميم للمُلّاك', bcSend: '✉ تعميم',
        bcSub: 'رسالة واحدة لكل مُلّاك المقاهي النشِطة. تُرسل باللغتين في نفس البريد.',
        bcSubjEn: 'العنوان (إنجليزي)', bcSubjAr: 'العنوان (عربي)',
        bcBodyEn: 'النص (إنجليزي)', bcBodyAr: 'النص (عربي)',
        bcTier: 'الفئة', bcTierAll: 'الكل', bcPreview: 'معاينة الجمهور', bcSendGo: 'إرسال',
        bcAudience: 'سيصل إلى', bcOwners: 'مالك', bcNoEmail: 'بلا بريد', bcSent: 'تم الإرسال إلى',
        bcConfirm: 'تأكيد الإرسال؟ لا يمكن التراجع.',
        // misc
        subACTIVE: 'نشِط', subTRIAL: 'تجريبي', subPAST_DUE: 'متأخر', subEXPIRED: 'منتهٍ',
        subCANCELLED: 'ملغى', subPENDING_PAYMENT: 'بانتظار الدفع',
        cyc_MONTHLY: 'شهري', cyc_YEARLY: 'سنوي', cyc_ONE_TIME: 'مرة واحدة',
        peopleSearch: 'ابحث بالاسم أو البريد أو المقهى…', auditDetail: 'التفاصيل',
        refresh: 'تحديث', none: '—', copy: 'نسخ', of: 'من', },
  en: { restaurants: 'Restaurants', cur: 'OMR', logoutT: 'Logout',
        kTotal: 'Total restaurants', kActive: 'Active', kInactive: 'Inactive', kNew: 'New this month',
        kOrders30: 'Orders · 30 days', kRevenue30: 'Revenue · 30 days',
        search: 'Search name or slug…', all: 'All', active: 'Active', inactive: 'Inactive', newR: '＋ New restaurant',
        thName: 'Restaurant', thContact: 'Contact', thVat: 'VAT', thStatus: 'Status', thCreated: 'Created',
        thOrders30: 'Orders 30d', thRevenue30: 'Revenue 30d', thLastOrder: 'Last order',
        featTitle: 'What each plan includes', featCol: 'Feature',
        featSub: 'Changing a box applies to every café on that plan, straight away.',
        featOnConfirm: 'Include this feature for every café on this plan?',
        featOffConfirm: 'Remove this feature from every café on this plan?',
        feat_PRO_ANALYTICS: 'Advanced analytics', featd_PRO_ANALYTICS: 'Funnel, item conversion, market basket, staff, forecast',
        feat_FULL_HISTORY: 'Full history', featd_FULL_HISTORY: 'Query any date range instead of a recent window',
        feat_LOYALTY: 'Loyalty programme', featd_LOYALTY: 'Stamps, rewards and member admin',
        feat_MULTI_BRANCH: 'Multiple branches', featd_MULTI_BRANCH: 'More than one branch',
        feat_QR_CUSTOMIZATION: 'QR customisation', featd_QR_CUSTOMIZATION: 'Centre logo, colour and font on the badge',
        close: 'Close', priceFromPlan: 'From the plan’s list price — only Enterprise is negotiable', tierFromSub: 'set by the subscription', tierChangeWarn: '⚠ Changing the plan changes what this café can open, the moment you save.', dwLive: 'Live', dwNotLive: 'Still setting up', dwStepsDone: 'of 5 done',
        dwFix: 'Fix', dwGoBilling: 'Billing & payments', dwGoHistory: 'This café’s history',
        dwPaidTo: 'Paid to', dwNoSub: 'No subscription', dwLastChange: 'Last change', dwNoChange: 'No changes yet',
        dwDetails: 'Café details', dwMore: 'More', dwContact: 'Contact',
        dwToday: 'Today', dw30d: '30 days', dwRev: 'Revenue',
        billForCafe: 'Showing one café', billClearFocus: '✕ Show all',
        auditForCafe: 'Showing one café', auditClearFocus: '✕ Show all',
        activity: 'Activity', aToday: 'Orders today', a30d: 'Orders · last 30 days', aRev30: 'Revenue · last 30 days (completed)',
        aTotal: 'Orders all-time', aBranches: 'Branches', aItems: 'Menu items', aLast: 'Last order',
        never: 'No orders yet', justNow: 'just now', minAgo: 'm', hrAgo: 'h', dayAgo: 'd',
        info: 'Details', slug: 'Slug', phone: 'Phone', email: 'Email', vat: 'VAT', created: 'Created', currency: 'Currency',
        subscription: 'Subscription', plan: 'Plan', cycle: 'Cycle', price: 'Price', status: 'Status', noSub: 'No subscription', addSub: 'Add subscription', editSub: 'Edit subscription',
        oneTime: 'One-time access', lifetime: 'Lifetime',
        endDate: 'Ends', renew: 'Renew', renewed: 'Subscription renewed', expired: 'Expired', expiringSoon: 'Expiring soon',
        activate: 'Activate', deactivate: 'Deactivate', save: 'Save', cancel: 'Cancel', create: 'Create',
        createT: 'Create restaurant', createP: 'Creates the restaurant, a first branch, an optional owner account, and a trial subscription in one go.',
        rName: 'Restaurant name', rNameAr: 'Name in Arabic', rNameEn: 'Name in English',
        nameHint: 'The name follows the language the viewer is using. Fill both so an Arabic name never shows up inside an English page.',
        rSlug: 'Slug', rPlan: 'Plan', rBranch: 'First branch name', rPlanStd: 'Standard', rPlanPro: 'Pro', rPlanEnt: 'Enterprise',
        oName: 'Owner name', oNameAr: 'Owner name (Arabic)', oNameEn: 'Owner name (English)', oEmail: 'Owner email', oPass: 'Password',
        loginTitle: 'Serva. platform', loginSub: 'Platform admin sign-in', createdOk: 'Created', saved: 'Saved', enabled: 'On', disabled: 'Off',
        planLabel: 'Plan',
        branches: 'Branches', branchesAdd: '＋ Branch', branchName: 'Name',
        branchNameAr: 'Branch name (Arabic)', branchNameEn: 'Branch name (English)', branchAddr: 'Address', branchPhone: 'Phone',
        branchAddOk: 'Branch created', branchAdding: '…', noBranches: 'No branches yet', deactivateBranch: 'Deactivate', activateBranch: 'Activate',
        profile: 'Profile', editProfile: 'Edit profile', editProfileSub: 'Update your name and phone on the platform account.',
        fullName: 'Full name', fullNameAr: 'Name in Arabic', fullNameEn: 'Name in English', profileSaved: 'Profile saved',
        language: 'Language', arabic: 'Arabic', english: 'English',
        changePassword: 'Change password', changeEmail: 'Change email',
        changePwSub: 'Enter your current password, then a new one.', changeEmailSub: 'Enter your current password and new email.',
        currentPw: 'Current password', newPw: 'New password', confirmPw: 'Confirm new password', newEmail: 'New email',
        pwChanged: 'Password changed', pwTooShort: 'Use at least 8 characters', pwMismatch: 'Passwords don’t match',
        emailChanged: 'Email changed', emailInvalid: 'Enter a valid email', role_PLATFORM_ADMIN: 'Platform admin',
        navRestaurants: 'Restaurants', navPlans: 'Plans',
        plansTitle: 'Pricing plans', plansSub: 'Edit each tier’s pricing. The tier is what decides a café’s features. Prices are in OMR.',
        colTier: 'Tier', colName: 'Name', colMonthly: 'Monthly', colSetup: 'Setup fee', colStatus: 'Status', colUnlocks: 'Unlocks',
        edit: 'Edit', planNamePh: 'Display name', planSaved: 'Plan saved',
        priceChangeWarn: 'The new price applies to every café on this tier, straight away.',
        perMo: '/mo', planOn: 'Active', planOff: 'Hidden', custom: 'Custom', choosePlan: 'Choose tier', setupShort: 'setup',
        tierStdDesc: 'Core dashboard', tierProDesc: '+ Full analytics', tierEntDesc: '+ Reserved / SLA',
        menuSect: 'Menu', importMenu: '⇪ Import menu (JSON)', importTitle: 'Import menu (JSON)',
        importHint: 'Paste a full menu as JSON (categories & items). Photos are added manually later. This replaces this café’s whole current menu.',
        importPlace: 'Paste JSON here…', importSample: 'Insert sample', importReview: 'Review', importBad: 'Invalid JSON',
        importWarn: 'Everything in this café’s menu is deleted, then replaced with the JSON. This cannot be undone.',
        willDelete: 'Will delete', willAdd: 'Will add', importConfirm: 'Replace menu', importing: 'Importing…',
        importDoneT: 'Import complete', importErrorsT: 'Errors', closeBtn: 'Close', catsWord: 'categories', itemsWord: 'items',
        // pipeline
        navPipeline: 'Pipeline', pipelineTitle: 'Pipeline',
        pipeSub: 'Cafés that asked for access from the landing page. Move them until they are a real café.',
        pipeNew: 'New', pipeContacted: 'Contacted', pipeConverted: 'Converted', pipeArchived: 'Archived',
        pipeEmpty: 'Nothing here', pipeAll: 'All', pipeWaiting: 'Waiting',
        pipeCall: 'Mark contacted', pipeArchive: 'Archive', pipeReopen: 'Reopen', pipeConvert: '➜ Create the café',
        pipeNote: 'Call notes', pipeNotePh: 'What did they say? When do we call back?',
        pipeTheirNote: 'What they wrote', pipeSaveNote: 'Save note', pipeNoteSaved: 'Note saved',
        pipeCity: 'City', pipeOpenCafe: 'Open café', pipeContactedAt: 'Contacted',
        // onboarding wizard
        wizTitle: 'Set up a new café', wizFromLead: 'From a request',
        wizStep1: 'Café', wizStep2: 'Owner', wizStep3: 'Subscription', wizStep4: 'Review',
        wizNext: 'Next', wizBack: 'Back', wizFinish: 'Create the café', wizCreating: 'Creating…',
        wizNeedName: 'Give the café a name in at least one language',
        wizNeedSlug: 'There’s no English name to build a web address from. Type a slug in Latin letters — it becomes the café’s address.',
        wizNeedOwner: 'Enter the owner’s email and a password of at least 8 characters — or switch the owner account off.',
        wizOwnerSkip: 'The owner can be added later — the café is created without a login.',
        wizOwnerHint: 'The owner is emailed their sign-in details as soon as the café is created.',
        wizSubHint: 'The subscription starts as a trial. Record the transfer on the billing board to make it active.',
        wizReviewHint: 'Check before creating — the café, its first branch, the owner account and the subscription are all made at once.',
        wizNoOwner: 'No owner account', wizOwnerToggle: 'Create the owner’s account now',
        // activation checklist
        actTitle: 'Activation', actDone: 'done', actLeft: 'to do',
        actOwner: 'Owner account', actBranch: 'Branch', actMenu: 'Menu items', actTables: 'QR tables', actOrder: 'First order',
        actLive: 'Live', actSetup: 'Still setting up',
        // billing
        navBilling: 'Billing', billTitle: 'Billing & renewals',
        billMrr: 'MRR', billArr: 'ARR', billThisMonth: 'Collected this month',
        billLastMonth: 'Last month', billOutstanding: 'Outstanding',
        billQAll: 'All', billQOverdue: 'Overdue', billQExpiring: 'Expiring', billQTrial: 'Trial', billQActive: 'Active',
        billCafe: 'Café', billPlan: 'Plan', billPrice: 'Price', billEnds: 'Ends', billLastPaid: 'Last paid',
        billPaidTotal: 'Paid to date', billDaysLeft: 'd', billOverdueBy: 'overdue',
        billRecord: 'Record payment', billRecordT: 'Record a payment',
        billAmount: 'Amount', billMethod: 'Method', billRef: 'Transfer reference', billPaidOn: 'Paid on',
        billNote: 'Note', billExtend: 'Extend the term and make it active',
        billExtendHint: 'Turn this off for a part payment or a correction that should not move the dates.',
        billSaved: 'Payment recorded', billHistory: 'Payment history', billNoPayments: 'No payments recorded',
        billRefund: 'A negative amount files a refund or correction',
        // people
        navPeople: 'People', peopleTitle: 'People',
        peopleSub: 'Every account on the platform. This is where you get a locked-out owner back in.',
        peopleUser: 'User', peopleCafe: 'Café', peopleRole: 'Access', peopleStatus: 'Status',
        peopleOwner: 'Owner', peopleStaff: 'Staff', peopleAdmin: 'Platform admin', peoplePending: 'Invite pending',
        peopleReset: 'Reset password', peopleResetT: 'Set a new password',
        peopleResetSub: 'A temporary password is generated and shown once. It cannot be looked up again.',
        peopleResetGo: 'Set and show it', peopleResetDone: 'Temporary password',
        peopleResetMailed: 'Also emailed to them', peopleResetNotMailed: 'No email on the account — read it out to them.',
        peopleCopy: 'Copy', peopleCopied: 'Copied', peopleNoCafe: 'Platform',
        // impersonation
        impEnter: '⇥ Enter as café', impTitle: 'Support session',
        impSub: 'Opens the café’s dashboard with the owner’s access for 30 minutes. It is written to the audit log.',
        impGo: 'Enter now', impBanner: 'You are inside', impExit: 'Back to the platform console',
        impLeft: 'left', impStarted: 'Support session opened',
        // audit
        navAudit: 'Audit', auditTitle: 'Audit log',
        auditSub: 'Everything the platform admins did. Read-only.',
        auditWho: 'Who', auditWhat: 'Did', auditTarget: 'To', auditWhen: 'When', auditEmpty: 'Nothing logged yet',
        act_CAFE_CREATED: 'Created café', act_CAFE_ACTIVATED: 'Activated café', act_CAFE_DEACTIVATED: 'Deactivated café',
        act_CAFE_RENEWED: 'Renewed term', act_PLAN_CHANGED: 'Changed tier',
        act_LEAD_CONVERTED: 'Converted a request', act_SUBSCRIPTION_CHANGED: 'Edited subscription', act_PAYMENT_RECORDED: 'Recorded payment',
        act_PASSWORD_RESET: 'Reset a password', act_USER_DEACTIVATED: 'Deactivated user', act_USER_ACTIVATED: 'Activated user',
        act_IMPERSONATED: 'Support session', act_BROADCAST_SENT: 'Broadcast', act_MENU_IMPORTED: 'Imported menu',
        // health
        navHealth: 'Health', healthTitle: 'Platform health',
        healthRadar: 'Cafés needing attention', healthRadarSub: 'Worst first: gone quiet, shrinking, or never got started.',
        healthAllWell: 'Every café looks healthy', healthWhy: 'Why',
        whySilent: 'Silent', whyDropping: 'Dropping', whyNeverLive: 'Never started', whySetup: 'Setup unfinished',
        healthDays: 'd since an order', healthDrop: 'vs last week',
        healthTrends: 'Trend', trendOrders: 'Orders', trendRevenue: 'Revenue', trendSignups: 'New cafés',
        trend30: '30 days', trend90: '90 days', trend365: 'Year',
        // broadcast
        bcTitle: 'Broadcast to owners', bcSend: '✉ Broadcast',
        bcSub: 'One message to every active café owner. Both languages go in the same email.',
        bcSubjEn: 'Subject (English)', bcSubjAr: 'Subject (Arabic)',
        bcBodyEn: 'Message (English)', bcBodyAr: 'Message (Arabic)',
        bcTier: 'Tier', bcTierAll: 'All', bcPreview: 'Preview audience', bcSendGo: 'Send',
        bcAudience: 'Reaches', bcOwners: 'owners', bcNoEmail: 'no email', bcSent: 'Sent to',
        bcConfirm: 'Send it? This cannot be taken back.',
        // misc
        subACTIVE: 'Active', subTRIAL: 'Trial', subPAST_DUE: 'Overdue', subEXPIRED: 'Expired',
        subCANCELLED: 'Cancelled', subPENDING_PAYMENT: 'Awaiting payment',
        cyc_MONTHLY: 'Monthly', cyc_YEARLY: 'Yearly', cyc_ONE_TIME: 'One-time',
        peopleSearch: 'Search name, email or café…', auditDetail: 'Detail',
        refresh: 'Refresh', none: '—', copy: 'Copy', of: 'of', },
};
